# Generated by Django 2.2.4 on 2020-12-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuoteManager',
        ),
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
